const STATES = [
  {id: "1ac", name: "Acre"},
  {id: "1am", name: "Amazonas"},
  {id: "1ap", name: "Amapá"},
  {id: "1pa", name: "Pará"},
  {id: "1ro", name: "Rondônia"},
  {id: "1rr", name: "Roraima"},
  {id: "1to", name: "Tocantins"},
  {id: "2al", name: "Alagoas"},
  {id: "2ba", name: "Bahia"},
  {id: "2ce", name: "Ceará"},
  {id: "2ma", name: "Maranhão"},
  {id: "2pb", name: "Paraíba"},
  {id: "2pe", name: "Pernambuco"},
  {id: "2pi", name: "Piauí"},
  {id: "2rn", name: "Rio Grande do Norte"},
  {id: "2se", name: "Sergipe"},
  {id: "3df", name: "Distrito Federal"},
  {id: "3go", name: "Goiás"},
  {id: "3ms", name: "Mato Grosso do Sul"},
  {id: "3mt", name: "Mato Grosso"},
  {id: "4es", name: "Espírito Santo"},
  {id: "4mg", name: "Minas Gerais"},
  {id: "4rj", name: "Rio de Janeiro"},
  {id: "4sp", name: "São Paulo"},
  {id: "5pr", name: "Paraná"},
  {id: "5rs", name: "Rio Grande do Sul"},
  {id: "5sc", name: "Santa Catarina"}
];

export default STATES;
